### ISSUE TITLE
언어 사용에 대하여 제안합니다.

### ISSUE THREAD

**Issue by ysw421** [MCPE-PC/2024-dimigo-1person-1project#2]
참고: [[링크](https://sites.google.com/view/energy-efficiency-languages/results)]

C#은 C 언어에 비하여 평균적으로 4배 이상의 에너지가 사용되며, 10배에 가까운 시간을 필요로 합니다.
다른 말로, **C#은 친환경적이지 못한 언어**입니다.
이 외에도 C#의 문제점은 @김혁준 선생님의 말씀을 되세기면 충분히 알 수 있습니다.

따라서 C#이 아닌 **C언어를 사용할 것을 제안합니다!**

**Comment by MCPE-PC** [comment]
@ysw421 의견 고맙습니다. :100:

하지만 저는 C#이나 Rust를 사용할 것입니다.

대규모 네트워크 트래픽을 감당할 수 있으면서, 사용할 만하고, 아직 사용 경험이 적어 자기 발전에 적당하며 향후 많이 사용할 것으로 예상되는 것을 기준으로 프로그래밍 언어를 선정하였습니다.

C가 아닌 다른 프로그래밍 언어를 추천해주시려면 새 Issue를 열어주시기 바랍니다.

의견을 수용하지 못해 죄송합니다. :bow:
